// GENERATED by scripts/sync-frames.ts — do not edit by hand.
// Add or remove images in public/images/industries/<folder>/ and re-run it.
import type { Media } from "./home";

export const industryFrames: Record<string, Media[]> = {
  "contractor": [
    {
      "src": "/images/industries/contractor/1.png",
      "alt": "Contractor on site, step 1"
    },
    {
      "src": "/images/industries/contractor/2.png",
      "alt": "Contractor on site, step 2"
    },
    {
      "src": "/images/industries/contractor/3.png",
      "alt": "Contractor on site, step 3"
    },
    {
      "src": "/images/industries/contractor/4.png",
      "alt": "Contractor on site, step 4"
    }
  ],
  "medspa": [
    {
      "src": "/images/industries/medspa/1.png",
      "alt": "Med spa treatment, step 1"
    },
    {
      "src": "/images/industries/medspa/2.png",
      "alt": "Med spa treatment, step 2"
    },
    {
      "src": "/images/industries/medspa/3.png",
      "alt": "Med spa treatment, step 3"
    },
    {
      "src": "/images/industries/medspa/4.png",
      "alt": "Med spa treatment, step 4"
    },
    {
      "src": "/images/industries/medspa/5.png",
      "alt": "Med spa treatment, step 5"
    }
  ],
  "realestates": [
    {
      "src": "/images/industries/realestates/1.png",
      "alt": "Real estate walkthrough, step 1"
    },
    {
      "src": "/images/industries/realestates/2.png",
      "alt": "Real estate walkthrough, step 2"
    },
    {
      "src": "/images/industries/realestates/3.png",
      "alt": "Real estate walkthrough, step 3"
    },
    {
      "src": "/images/industries/realestates/4.png",
      "alt": "Real estate walkthrough, step 4"
    },
    {
      "src": "/images/industries/realestates/5.png",
      "alt": "Real estate walkthrough, step 5"
    }
  ]
};
