// Rebuilds the industry hover sequences from what is actually on disk.
// Run: node --env-file=.env.local scripts/sync-frames.ts
//
// Drop images into public/images/industries/<folder>/ named 1, 2, 3 … and run
// this. It writes src/content/industry-frames.ts and updates the live row, so
// the number of frames always matches the number of files — no hand-editing a
// list that goes stale the moment a seventh image appears.
import fs from "node:fs";
import path from "node:path";
import { neon } from "@neondatabase/serverless";

const ROOT = "public/images/industries";

/** Which card each folder belongs to, by card title. */
const CARD_BY_FOLDER: Record<string, string> = {
  medspa: "Aesthetics & Medspas",
  realestates: "Real Estate",
  contractor: "Contractors",
};

/** Alt text for frame n of a folder. */
const LABEL: Record<string, string> = {
  medspa: "Med spa treatment",
  realestates: "Real estate walkthrough",
  contractor: "Contractor on site",
};

const numeric = (file: string) => Number(file.replace(/\D+/g, "")) || 0;

const folders = fs.existsSync(ROOT)
  ? fs.readdirSync(ROOT, { withFileTypes: true }).filter((d) => d.isDirectory())
  : [];

const sets: Record<string, { src: string; alt: string }[]> = {};

for (const dir of folders) {
  const files = fs
    .readdirSync(path.join(ROOT, dir.name))
    .filter((f) => /\.(png|jpe?g|webp|avif)$/i.test(f))
    // by the number in the name, not alphabetically — "10" sorts before "2"
    // as a string, which would shuffle any sequence past nine
    .sort((a, b) => numeric(a) - numeric(b));

  sets[dir.name] = files.map((file, i) => ({
    src: `/${ROOT.replace(/^public\//, "")}/${dir.name}/${file}`,
    alt: `${LABEL[dir.name] ?? dir.name}, step ${i + 1}`,
  }));

  console.log(`  ${dir.name.padEnd(14)} ${files.length} frames  ${files.join(" ")}`);
}

/* ---------------------------------------------------------------- file -- */

const generated = `// GENERATED by scripts/sync-frames.ts — do not edit by hand.
// Add or remove images in public/images/industries/<folder>/ and re-run it.
import type { Media } from "./home";

export const industryFrames: Record<string, Media[]> = ${JSON.stringify(sets, null, 2)};
`;
fs.writeFileSync("src/content/industry-frames.ts", generated);
console.log("\nwrote src/content/industry-frames.ts");

/* ------------------------------------------------------------------ db -- */

if (!process.env.DATABASE_URL) {
  console.log("DATABASE_URL not set — file written, live row left alone");
  process.exit(0);
}

const sql = neon(process.env.DATABASE_URL);
const rows = await sql`select data from site_content where key = 'home'`;
if (!rows[0]) {
  console.log("no home row — nothing to update");
  process.exit(0);
}

type Card = { title: string; frames?: unknown[] };
const data = rows[0].data as Record<string, { cards?: Card[] }>;
const cards = data.industries?.cards ?? [];

const framesFor = (title: string) => {
  const folder = Object.keys(CARD_BY_FOLDER).find(
    (key) => CARD_BY_FOLDER[key] === title,
  );
  return folder ? (sets[folder] ?? []) : [];
};

const industries = {
  ...data.industries,
  cards: cards.map((card) => ({ ...card, frames: framesFor(card.title) })),
};

await sql`
  update site_content set data = ${JSON.stringify({ ...data, industries })}::jsonb,
                          updated_at = now()
  where key = 'home'`;

console.log("live row updated:");
for (const card of industries.cards) {
  console.log(`  ${card.title.padEnd(24)} ${card.frames?.length ?? 0} frames`);
}
process.exit(0);
